apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-bedrock-survival
  namespace: flux-system
spec:
  interval: 30m
  path: clusters/main/kubernetes/apps/minecraft-bedrock-survival/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

