apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wY6LMsVeooMTXls+MmnAQFsTgyqEOcWpmavnFluHogBH2JlrjdsqeAgRC0HPyq9HSV3tX8Bl7t2Jjm8F1ybQSRAeXKq09smEZx4XhZGe3ssYpYQ7wDw8HctYE1eKJRXFlnbrdDpaejU7HtOWCVDEKk+pMsb6sHLuEN7wmzYSDBy5X+JgO772Z9jnDXej0mw8KNrBQjsaTKJ8a8DQaUrMTplwDLiRT3NpX/Td50FDiX7KzvMJ+LYsvuIBNY1EiephzQKMaPduI82UYZq1gLDnlln7NOLnKM3wmmMcCL+KFixZ0ndoM36TaFYsmiK4iyETeRy7QOJGYsoN83CZGa2f0tkinLY6wfHJdHeoU6RFxbjyDmIgR60QkMAYJWvajOl4,iv:7o5OoytKm2L0PtIYBeV7+DoWJX2lzctwAVvMPUb8erc=,tag:2Z8KLcJu8w5733dzp2Fq6A==,type:str]
    identity.pub: ENC[AES256_GCM,data:yW2utANnSFl4p4SRyYJolR7+/0PkthP/6gJTIEeluATt3gWanxDrtEIZEPKtGD+jAExCOjT37HObgfoL5kqzShoGg/oi8LMOJT8BBUu1TsBwkrqs10Hx9oBf0ulMLNs2wJ/nnzUI5Ax9KzRik33aP1LLCVvRNS/P552ugod7v/q1VfjuGAzYegesbIGIsVAhMKUyez+ce/J0zph17egf42oNSgavEB5yxkpJl+Fb2L9T3iqSxg4pfCjoSGFM0oRg2NEWS5uSqgKFnolaUA==,iv:NKAfP50uicGIuEKhUMu8fruMz1wEi2LkkO8Ii03BnZU=,tag:N1Ii/HuZZ/haZA/B49FjYQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:BYfD8WV+YzWcOM80yWHpd6zucR90w/aWRf0HZlpY3WSHVgk7IgnafFbJwSiMtJGc4EzaZuysVWyx5Ktca4sn6bwv4P5KRsJQDAIkCefSDzUd/fEebhvTmQNHCjNxkDqA7jw8vnayKaa25tRrfXhaEo00sfaclNOV5MQO1/EPVshj9W321PHnUIlLeCcIWATfb/V1fB2cYuA91+qHkbLTMbE++m/ImxtibZS3,iv:79oFouRgcxQWHR2+8fdmu/Zhm5PATATPv01N2g/phHM=,tag:thtrta+dVjJMlHQHp/bTsg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1z8l6sn0ghl67y6m8gq2n7p6fz6zz394rug8r9dwfq5hn277njyvsza2rpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4eGo4YnFFY3BzUFM3RHcx
            OTFRbXhtSDVSdXFaaWpETDRmUnZyRWxsbUhrCkp6Q0RIUWxmeXpTVXFlUm9xZ0sx
            ZWVIeTU5MXRqQVNnV1pHYU9qUExkcmMKLS0tIDhIM3hTN3VCR3JtWnhCelh2dEtn
            VzVldjRWWFA1N1NaeEdUZVJnSDRRd00Kyyr5iIWZyy9cvgSezF3Zx33ZIS8owO5/
            V1sgwCJmVQ4wgHEK578DgC/9O+RWKApb79wMCjwSzj0iB6p6Nm3M6w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T14:31:18Z"
    mac: ENC[AES256_GCM,data:YhtT2xiJNmUXtwOZY5E141RSaqDGxHMapPnrlsLrJZsl6bzADY7UHwqpDbbnZEA298PI/U9dS2Ln9+jgCL5ni2XCrnEs9pZO1+T1ApKGrjq/FtbyD7GAOZgdMRZ5h/WJRcskdXVM5+YUtWVuGxMeAgA58nsIRU92jMrN03t2oYs=,iv:2Ph6nHKeMANQODhcXyDesujkCElz3qV0gjMIMSOKuiU=,tag:GoaWHwB5oZmMSFpg+EiYfQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
