apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:RIYwu1Aw0dCfKbKsCIwrfdUPtkydUmLT/xjKZkS6SI7dZrtrDSyExXyCJ4ZPTwiFWUkGJ8ftoarI3pDXYwjDP96k3XmbRjYEl7kVBZhY37b4kc+K+cKXaP2RLgvvk3/znxzZdV2hvXK6uHhW64XDGfwibCj9Vqwsry2/fGkH6XC6rfmyjGyS/AbXvhNxr5P1QKKi3ueNOONs8dBKkYv9xyqphb8uJq1cMZcQEW4hj994bZWxmE5WK6inPeX/ilPjWPcEQtv3YwretH3ca6qAUNdcB5Obh+j3k+GCRuPxCPsRlaChx+LDiNhHYPcWKslvdvFGfhiPw60a864MDBp9AuM5t/V6SNbSdjQa19OV+tGeoV+CHmKx8oatQYxNfA+u,iv:LmraKrQaicDHgaMDCp09d8PWI7JqSGeg0Y+4/wxs/Ks=,tag:LNq/UWWsImOEc4TzEavXYw==,type:str]
    identity.pub: ENC[AES256_GCM,data:CabX6eh99JNvKT+04KEfdOrh8jwOD1wHeIrr9xJ352Fg5JD71QZGRQOc7spcdzZU+JUG9c7r7CewzgwkM2S5C5p2f25v8uszbEjWINl6NWpg3zT2ZIo2Ymw305ytv85/uz9LfTZHUcmWwZfM6hHDE/Qk+3EZ6vN8/uwrBffW99JJdY0eSjRx3K7e67zQVz88Hcfa6tPLx4oZ7bYirUh4mU9mPOQMXt+TVXE3faMcxcx771ePKrtnB54XGsQ5LLlcK1XWp8w1Xg6t/95LFg==,iv:j2U4It0pqa318GRVKAtj0aUHRGWcIiGQH4CfVQT4V04=,tag:fLLGda1HdnRaCa0w1X6LuA==,type:str]
    known_hosts: ENC[AES256_GCM,data:2QOupo3CNZvQlYPduaigeaUiDUETZSUdslywm0QvsJVyHjjWSSDyq2sl9jj7w/KTzIt56R46fVuH2KOLULYLdrfqUTVDTAZwpB43LiyaIla+WeuFuu9wRERuxEt33tRFho5QJt+w4DksoCIVMJLqU45CYLH3TionXkYYaGeIxaRSx6f0iBxMQsjz/N0EAwHM6Mf7Xn4yH/gVYFzFXHdaiaJZWIoWsn8vRd9Y,iv:W94m0lXcSKd/aIWi4m7FdlBo/c/GhoqRDUs93DckzvU=,tag:SCmnqHWJ8f73TRpnJHyn/g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1z8l6sn0ghl67y6m8gq2n7p6fz6zz394rug8r9dwfq5hn277njyvsza2rpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArSS9YRkNIZEhWOFRGUlAy
            bGNzaGZYQjgxY2xmQUlLTmhQM3ozcFVIUlNFCjFIN2dkeWRqd1ZRRm41MW93ZDA0
            R1VzcnZuNVJVZmhpRllLdnFUR2tTNDgKLS0tIFJQaE1XSldqeXhEQTNOMFQ5TzNS
            YTA0Lzd1djBCNlJsbCt2NFJhVGNGdmMKtJymUMwNoCeOclFfwuTHc6ScwHD00Tlb
            ITKy6bc7tLIcc/bBlXHWTLV1WeHg/GBcH0i+AzmdndzZBTNhIH/LRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T12:54:20Z"
    mac: ENC[AES256_GCM,data:t/uZH3Y1+Pl1KcM+bqSdCgiaqMCr6avnzxamGSNwm282trx2Q6lcCRcaPFttd8dr80bEUNJ8UWYfTjPo50Q46gwUv9uRVRr8BVh9aZgNGrdEBDZ7VEgCGn1qkDbL7MuwPIvS8K6joTHNP/c8OYOLB21Y/lBho/XmTr4bUjr7hOU=,iv:ygXkV32qVsGKPL8yGCosaAbtJbKjziK/6pntXbkZdxs=,tag:gCB434RK5t/78KEVEIN0cg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
