apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:rCPIFg1+g/YIGiXhStY3YslYo6IzmOlJy2UwO5tLj5bHtzU3yqZdXtJpHpU1O6Oe5AHl5DFyZ8qeUcwZ3DHw1TLNxrpaXVI9lxXCJ4H3RWGSizOfnXgIY0aU/EA3g04wcFQ13Z7fO+d/oS2FNszpe+f+EPziId5ku5B5L2AWSqrUSfsngNBVsToh0zcXzscvMVTtYwQa6/Nu71BGxc4r9xD5rGwrW2QZ3dgxpAVHvEF01UX720huXikYUN5KKFNopZnIW34scyO2XI8dFyxMNSo9oLk24DXf31pu54OIc1jcaMV0XmX5fZkNXnXLrNxMHvqbeTZfHeVPBFNwIHtXvw9NQGOJi4ror7KQhJMNh5vKFJ7vkMjz3iJlXAkKahVD,iv:haEinfXHx/0A7XvPw3GxY31PHmpvByCw2VRrCxOO/uM=,tag:D7g/yZ7GKY5EYq+k8c/WEg==,type:str]
    identity.pub: ENC[AES256_GCM,data:W6rPZHA/xNdRwZEPH3mU6NIXsIbd7h2IVZo0pMqL0jgUmLWo3Qo/1gzf+RJMxnba2Rqp9arUa78OUGrIeelbnD6M7p5pKsvHFwXgd9P7+Qu26kXXjNGpOuPSl3OG04DpWkco9AqfxDf6jGXrOWs1SIR/nEbOp5KEzNIELIx7JOTtOuGEyiN3LWskvuG3kM83Rc+Xizj6ZC520DFWmKyo/1YC8+7e3LoWWJSW+UvhyqFQ0TnqqIsyZVVGTIIPGVr27+KesW4nSsPLk7UDWA==,iv:GCA1BAr3tUM3nG7wSbttRUGo3DxooEcKpE6c/W5fQjY=,tag:vGQI3sOJziXcwlIkBwbQiA==,type:str]
    known_hosts: ENC[AES256_GCM,data:0IC5NCMvJ5vJ2W7Q7yQAAkwR0KVythNtKA3C8LsQkvxx7hkaDDKyi2JZGn3vzIjzYUqOzfUwhVS7fKsw2HphzxId8XrkfJcxifiGOOiSVDLz+j4MwjJc52IF5Pvy5Jl3OjFhZK3vOlH+H0QaIzgqZXrEbIYukjX0FHQfnsSzkbNgXEJuV2BR1cPJ5GGB7+38e4UthimQOxuvejpViRV9Xdgd6jZKEPFaQcSg,iv:fjRR37H7M8y84sYlDEiRRr8XsHndob/Wp8BRxCGcrh8=,tag:iPISGsB5tXJiSc1IFU/xlw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1z8l6sn0ghl67y6m8gq2n7p6fz6zz394rug8r9dwfq5hn277njyvsza2rpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTMVR4NXJXeFlGV3ljK2VT
            d1UrL2o1eFVWVGthblcrYVFQWnBZbURmNjJzClM4a2R2SytjUVhpUWRFUm1NL05S
            VHNKNGZzTE9ZZDlyQ3VWYW5pYWVjVTAKLS0tIGVvRWtOM00xMkpsOWZDUFVDOEVJ
            eVRYVVF1ekZmQk5Ha3VIOUl2YlJGRGMKTCtZfhXFk7LGwC6HDolZ+e7AClQcHgSy
            WWAQi58WhW5FbhmYeXjQ84TgDUZYWTQm/S+nfImICnaLdZRfwR0gTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T14:58:46Z"
    mac: ENC[AES256_GCM,data:catEvjKDUGWwKBOMDZErldHhA5BcXmMpSfPeBIp00YFVRfQcHp5P0U+QCZY5AOVNgdXdOACRp6AYkHw7tfXnvFEb1YyOg2pD9q6fWmyVEUCWvadZUVmbX5kCbH7XnJw5y7oIOEKkaJMTMBZ9aYEJQFN7DRdpX2A2jdSjIUVMUsc=,iv:ZsTe6uHwW+h1p2egC5VdlEsJPBLdCiyoI0hgXMXECnU=,tag:95hr5ykVjXtWA19D6coR8g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
