apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:QyeSR64hAK2klmvmintRL0yxcd7Tjzu5aZau8ah9nxM+DBJpMGM9V8hnyVQpES336968YfNNQh2FOnmWlBmHwQ/6Ld3GWrAtNnt7oOx38zYVOWo7o3uyUiVi6Jz6njgp3mccFfDlEqpPT+gFXLFnZib8zj/NV4tzWpN3+GHmr5n/6xMN1Dl3rYquTl3O8+ZgHZBSXIaU6yzdFtENAgsVbPrzjU0gM9vbZMv1Zy2UTzac1x349SyG2wQcFofXxynsIQkiC02ZDax59tCBWrdIhXI4cWo9Zr+ohLgIzY0R5Ie8949zhv2YMY6QseU9PkwnK5XHX1+Jy7L6k7x6Hx0uIaIRWplc6VKaCpsRXiP+wxBx7EDTa+zYHgAznHNEqli6,iv:KL//F/MPk3mScojXgbJHBeSxufPf+HoyHyxHTXh9KsI=,tag:PgrBTdRfJay3l9pCnhl2Vg==,type:str]
    identity.pub: ENC[AES256_GCM,data:KYBp702mFEUh/JHA7b06KCgsRjWeK5P/F40u1Wox9SsB4Hx8TqpGcRDbgNnPlusyUpjX/tiKy4w7QtzNSzhg4/dL4EGI2rq4sgEPD6dssoE7ok3a/FHOYb+qrGkdx9TWQbYpZZvkwdPS91JE3qLFWOjqlu0ZXIX701+ciSrR2yaqr+E2jblpYz1vuXuyBIRVrQJrawxxA6akwfMT3X+CdJl3xLritzf071HH29gBTmLdHP2feekshEGGB3nwSgMETvZR+80rLPGOkMYq1Q==,iv:Op43pViR8RCD9MfacU4k8OkEtJi5pZi31U2RIQfEwLU=,tag:1PD5qCYcVrNT8iLTG0tLYg==,type:str]
    known_hosts: ENC[AES256_GCM,data:9V9oMBQeyDUm5Kc6z1fIysGP0GYNuhji6RghgN8UrGIqLC8/Sf1LVrYYMkDHGMkEj9bt2tPNOdZhe9E7PpSdLlJC+Gm9gLkYKFTzkG6JIPLFck4Hajqr5OSq8VtM05Vo1/jmkT+Rb5umI5Pg0kMpmM/QiQmhRbInF6Z6JTcaCxgv1oaBTFlfM2ThmrnJ5esuVLmK07Za39sZOFUI4Ur6NYhmXhXHhvLcPOij,iv:Edg9e+RT/gB8ShNvJ6/MnNQVTiINiqTI+2q2lLcQQpU=,tag:kDwHUCgVN18pnWRjrev73w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1z8l6sn0ghl67y6m8gq2n7p6fz6zz394rug8r9dwfq5hn277njyvsza2rpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpdEtlLzlSZVhsMzluWUcx
            bFo3U1JJODZBTXUxOWRFRXpSb2IyQ09QdlEwCkQvVWVBTC9WQWlYNjluTmtaR0sv
            SVo0RmFobnd3MTBDL2xBZ3kzVHRPWUkKLS0tIHBTUmVlN0dxRzJvNUprYmFIWkY2
            UWVaOE1CUGtFcUV4Vm93dVl5U1lNTkkKZCwl4c5Wu55yQr3sIvwU+7PTFGvC0WRj
            ev9YCl4/P0QxoeNVJ4e31hh47Bz/UYlxhPKgQzad1zEwfsP2Abv9iA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-15T14:45:07Z"
    mac: ENC[AES256_GCM,data:35IQBiv6H5xLNqNqtFkn04XsH+Ur19AW6YGjf37Ut/RRJ2mfaZVOA/bmyoaj5pZJLdzsCCZVlisFnRBENZZXkreOK7HygkeqS8nevwaVFGGBIvLpQkhwfvvCvfywwMrhXhKWHoyd42GMVD2MErKx87d+2pKNw+7fQmy15Lf02/4=,iv:2KSlilHD7RWBKzWtct6Z2hGmJ9T4aJQvWXSJ8AfXhLY=,tag:tcm/czOiWnQlcco839UGLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
