apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:naGYUb0qU6btr9FYA7dsIDPD1WAbUAjgYYvhONrWcNsajqX2d6sNu4FHxgZXofPkJzhjO/52+D9WStqZduaZvFde04W3T5OjnPFXMYGxrHk9NRFeI0gj8LAkkMklQt6ProVLduPU+u+Ps5BLO4fqjhZenYjdaqLufnt8IOFyzeHMOuteuUopVQtG/z+qP1KRhioerfJ5KpY0pVOtmhLSYDOHWgriEewECu/bmroSZz9W41pp7f12CkyAiI7QCXAuCuoriBwoVTlSn3L4iLkcufE4hpWpXChu+KrbaIk6BHz8QCYKJdUG74DohRANPh7c/4rg/4YLmjTI9ZoAa/95YtvMH3Pr0tKJK5aKXyMCRThyGGYjwBDizpXjTbk/JtHc,iv:o/vVvPbMMBJzdHggo3nb3sCtEykGsy56OzcEufWQmwE=,tag:6f6yBrpGEah93QhFY4UDCg==,type:str]
    identity.pub: ENC[AES256_GCM,data:BKrmYL4WXpvoGD5qiNCrPnqktGlunwkqao6V7eGTKxfjbBRZ2mi7Q5+og0CMmZKAa5OHHC5GBV+PpxYm3p2ciwiIi1UBfUOFIbnCO100b6WEGr/aIkgUBJQF5+BiYvzr8ojtovN/Ncx8RRCjs2t+RpwwXyK7lJ5qP+oK3fpZJd2zja2a8u6C39hJonUF4gMGUM1dQ42kxw64YgBQYOufMMa/e84jYrj/G6DMINWXipY2fJb+J9icgF1FMlXwq6Ygz1egoge47+VKD1SFEA==,iv:xcSrbchtApFlvY+Rdz+Y8qwgWMFUG/oLdAr1bFOXiJg=,tag:ri9474kGRK379wPMIj7Lcg==,type:str]
    known_hosts: ENC[AES256_GCM,data:ABx2jpQm+R8bHjrQjlTRhbHxWtWa/Lm+L5RAo/fplVnGV2ofJw0QmkXunCPkvywPv+K+f558kXyfyC1tVUD3tPDbbuXYgGsNh4U6ZFQ7JQWtYtHWhx2WY/IbwQpfPU5JpOSguUgnKyip/DLgNhXbyYSeers/P8j1+PHnVtIeil3hh/o7A2r3ufunZ9oOZp8WfMiVblONpwD2jPlesWVDhf1S6C8aOlu+bQF5,iv:soVgFzv4Rubiw6nbdHprnvyjWB55VviG5lQXjEa1LG4=,tag:bhzdWCdpF6GQdrHrHknXpA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1z8l6sn0ghl67y6m8gq2n7p6fz6zz394rug8r9dwfq5hn277njyvsza2rpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDaEZTTVFtRnc1eWxpYVRv
            Tm0rSFEwSHpWTSt0QXdJN0VFZEVQTzhkWmk0CjhwS3hqVGsvdjlRZ2JOZ2Z4bjhV
            RW96WlRzWURYNjJzK2pNU2J5MUE0QXMKLS0tIGpJVHg5MlkxaW9MZGxRS2xmOUo4
            czV2ZXdiUTlPOEttaEZ3aUROWEJwQU0KRnTcXYjHiB//wA7Xg3xK7+U9LTg1JMu4
            ZRh+WyYI2zzUH5k7QG8FpV30db2f6knMCoiK/GA+rZOamlK3cnrehg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-19T09:13:31Z"
    mac: ENC[AES256_GCM,data:vMoSl3iuqT87aFt0kdazI4Exigi8TNv/F3zM0eyR+hdiNYpT/5LdZfigxd/7vJO59gBnNv88cfNttRObhbyeHtvkFbSNRjfRwCokKSv+KgePrc7CxlPV3IzpxLB9eL5dpZseaRZ2Mxy0+NgB0I5Zss/0pLYrhAZv7TmC65b3Vck=,iv:vfHhviAs1k+Habi3KCYL22VLXIJz2LRXr5mRPKtT+io=,tag:R7ysYYrGA2KMyhiwJYtDAA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
