apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xnHzqMf+f0y+upBTfDztfcCxXflb6ZtbBoA1Aginh5qdp4LZ2cEO5d3tI4wRBV4i+fLHxOsTkjzNsu3woZQOUPOgKxCiOzC08qrtRyKxkP9PZQYVz0XmkjaCZE3JACgq/gBJfkNLASXOz27wyDhKqcFAgczauZDV3NqE5gS1FgmVuLkBPyg0yKJHgPhYTWx9Ppe/QUN2KIevM+IPhLdA9oI5YaGQIeLjyJI3jMOcoE2B1I29XbIJkH26qZixb5YWK6XjxJIzV2A2IJ/o0bjrF8iSAlGwS2LSAnd+1LX/+ExqZlVVeoAkFjUuYIbbiMAladXPSO0cXhyN/EwzDe31ses6m/54yl7qDyWDSfqR5edyyR4TQ0hgQpV4Ji0dqZBk,iv:SKRnRBIx2/pH+FgY5Kxv3Ewm3MVCpQdBt47Bs/bJDRY=,tag:PI+3+aCvmQQkoj06U8hsew==,type:str]
    identity.pub: ENC[AES256_GCM,data:RLWdqi+GpP+8KauAitTneFLlev8OFWqgh1blfpxTnlCn3RE8dYideeCltmA9gTpCpO0VDa2ytDsnkQvOc+kadCtZ8zbP+kEKTk7zex15zYRP0piW4exXeVY3l6PTy/+oo3JX+reBPNP9LM057mmNG99F42IMdEvpsjf5nKjAJnHdv7uvwUW9M2/vDFFFDKZ0mslkyRvLmTcqp5JujeIpFPxbEFvH5q8mUz+6gOi084luWlgxfQqA9gXPEpmPax1S3UFTizv1aj2nm7bp1Q==,iv:swK78X97gxq52drRqVvPrcbTKQ6NRd0qVsYmzaCqO5A=,tag:YIlLClqwoUthvaP+5gK6Xw==,type:str]
    known_hosts: ENC[AES256_GCM,data:jkl8j41Zyw9kWsyOqVVIDpb7oL/9o9umLLsgmyHpZISNy7vDy8LA6muZyroieALj/qxC2uzGXPpq7AiyQ27FJTQ5nJbCYIc0QYxJb1fCUP8JsXhcbI0Njq36W80r0b/SG2QGouK+EcUxZjL8RpCMQJwopJjWeSLd4Npr3ftXGYH1jg+01wHiW2pX0PTvocM8CMt3TlDyYcUJtdAbfvRZYw1f/nFCWvakTAnC,iv:jOl/6eusJNjFvO4+kAA+69rI4N/1xlBBFpoN7ivbLaA=,tag:Bc+UpROCJVnG1Sb7ZTfiGA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1z8l6sn0ghl67y6m8gq2n7p6fz6zz394rug8r9dwfq5hn277njyvsza2rpy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBybUhSb0thMmlBeEFOYkV4
            cmZPSHZsajhsbkZSdzhHM1pLN1VsTGxnakV3CmV1dDlkVkVTTVdQdWpwY3FTZzJ2
            cXBBc3lvY0lGaHdKTzhVVEhseTM2cW8KLS0tIFVsMWM4Z1lvMVJpTkdjeERNRGU4
            K0Y0VlN4WE8yQzFmMktCaFcrS3JDTnMKDsa3DsJ9Yt1mnTS2yFIEvUkrmDTsGGoJ
            eGXDhKL4wFDsoa2AJuTvTFBPv3zrJxTH2Y/mtlZawO2QtjZ32oBfHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-17T12:04:45Z"
    mac: ENC[AES256_GCM,data:yO525ZjQS2f2NOU55uCWaA1ERXP+bY2ZbyazcelFu5Ah4JrIteOnQjLqtCJA3F1/vNRypuQqqmcDs/oQ1+F94yNt+R66ydeE1cq5Y5XKmgcgjf+xJ6vDe3HseYPPFxSLa6Ni6IvGPnFxtqioFpF1Wdi+fCebISMezy0/joSSHG0=,iv:Z0Q5TlhmLDt7yiHqWGivKlOV7tUrKy8+x51PLcLtNBs=,tag:le91mIQRkGcfNwnIv+O3yQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
