apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
    name: helm-repos
    namespace: flux-system
resources:
  - bjw-s.yaml
  - cilium.yaml
  - cloudnative-pg.yaml
  - coredns.yaml
  - descheduler.yaml
  - intel.yaml
  - jetstack.yaml
  - kubernetes-sigs-metrics-server.yaml
  - kustomization.yaml
  - longhorn.yaml
  - metallb.yaml
  - metrics-server.yaml
  - node-feature-discovery.yaml
  - openebs.yaml
  - postfinance.yaml
  - prometheus-community.yaml
  - spegel.yaml
  - truecharts.yaml
  - home-ops-mirror.yaml
  - emberstack.yaml
