apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: minecraft-mussoncraft
  namespace: flux-system
spec:
  interval: 30m
  path: clusters/main/kubernetes/apps/minecraft-mussoncraft/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

